/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author chechajosue
 */
public class Juego extends javax.swing.JFrame {

    int puntos = 0;
    Jugador jugador;
    GenerarPotenciadores generarPotenciadores;
    MovimientoAliens movimientoAliens;
    ArrayList<Alien> aliens = new ArrayList<>();
    ArrayList<Bala> balas = new ArrayList<>();
    ArrayList<Potenciador> potenciadores = new ArrayList<>();
    
    public Juego() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        inicializarPartida();
        this.setVisible(true);
    }

    
    public void actualizarPuntos(int puntos){
        this.puntos += puntos;
        this.lblPuntos.setText(String.valueOf(this.puntos));
        this.repaint();
    }
    
    public void inicializarPartida(){
        jugador = new Jugador((this.getWidth()/2)-32, this.getHeight()-100, this);
        generarAliens();
        movimientoAliens = new MovimientoAliens(aliens, this, jugador);
        movimientoAliens.start();
        generarPotenciadores = new GenerarPotenciadores(this);
    }
    
    public void generarAliens(){
        int posY = 0;
        
        // Aliens tipo 3
        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 8; j++) {
                aliens.add(new Alien(3, j*64, posY, this));
            }
            posY += 64;
        }
        
        // Aliens tipo 2
        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 8; j++) {
                aliens.add(new Alien(2, j*64, posY, this));
            }
            posY += 64;
        }
    }
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPuntos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lblPuntos.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        lblPuntos.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(476, Short.MAX_VALUE)
                .addComponent(lblPuntos)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(853, Short.MAX_VALUE)
                .addComponent(lblPuntos)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
        int tecla = evt.getKeyCode();
        
        switch(tecla){
            
            case KeyEvent.VK_LEFT:
                jugador.moverIzquierda();
                break;
                
            case KeyEvent.VK_RIGHT:
                jugador.moverDerecha();
                break;
                
            case KeyEvent.VK_SPACE:
                balas.add(new Bala(this));
                break;
                
            case KeyEvent.VK_ESCAPE:
                
                movimientoAliens.suspend();
                generarPotenciadores.suspend();
                
                for (Bala bala : balas) {
                    bala.suspend();
                }
                for (Potenciador poten : potenciadores) {
                    poten.suspend();
                }
                
                Object [] opciones = {"Regresar al menú", "Continuar"};
                int respuesta = JOptionPane.showOptionDialog(null, "Juego pausado", "Pausa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
                System.out.println("respuesta: " + respuesta);
                
                if(respuesta == 0){
                    // Terminar el juego y regresar al menú
                    System.out.println("Juego terminado");
                    return;
                }
                movimientoAliens.resume();
                generarPotenciadores.resume();
                
                for (Bala bala : balas) {
                    bala.resume();
                }
                for (Potenciador poten : potenciadores) {
                    poten.resume();
                }
                break;
        }
        
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPuntos;
    // End of variables declaration//GEN-END:variables
}
